name: Build and Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install stgrid2area
        run: |
          python3 -m pip3 install --upgrade pip
          pip3 install -r requirements.txt
          python3 setup.py install

      - name: Run tests
        run: pytest