name: Build, Test, and Publish

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          python3 setup.py install

      - name: Install PyTest
        run: pip3 install pytest

      - name: Run tests
        run: pytest

  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: build-and-test
    runs-on: ubuntu-24.04
    environment: release
    permissions:  
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build the package
        run: |
          pip3 install build
          python3 -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
